[build]
builder = "nixpacks"

[deploy]
startCommand = "composer install && php -S 0.0.0.0:$PORT -t ."
healthcheckPath = "/"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["php81", "php81Extensions.curl", "php81Extensions.json"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader"
]
