[build]
builder = "nixpacks"
buildCommand = "composer install"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t ."
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["php", "php81Extensions.curl", "php81Extensions.json"]
